name: publish on release [auto]

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: macos-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: install rustfmt
        run: rustup component add rustfmt
      - name: rustfmt check
        run: cargo fmt --all -- --check
      - name: install clippy
        run: rustup component add clippy
      - name: cargo clippy
        run: cargo clippy --all-features --all-targets         
      - name: install cargo bump
        run: cargo install cargo-bump          
      - name: bump version
        run: cargo bump ${{ github.ref_name }}
      - name: push
        run: git push origin main
      - name: cargo publish
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}  